services:
  hms_api:
    container_name: hms_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - hms_db
  hms_db:
    container_name: hms_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_USER
      POSTGRES_USER: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
