services:
  hms_api:
    container_name: hms_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
    depends_on:
      - hms_db
  hms_db:
    container_name: hms_db
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
